# Generated by Django 5.2.5 on 2025-01-13 04:19

import uuid
from django.db import migrations, models


def generate_guids_for_existing_users(apps, schema_editor):
    """Generate GUIDs for existing users"""
    User = apps.get_model('users', 'User')
    db_alias = schema_editor.connection.alias
    
    # Get all users without GUID
    users = User.objects.using(db_alias).filter(guid__isnull=True)
    
    for user in users:
        user.guid = uuid.uuid4()
        user.save(using=db_alias, update_fields=['guid'])
    
    print(f"Generated GUIDs for {users.count()} existing users")


def reverse_generate_guids(apps, schema_editor):
    """Reverse operation - set GUIDs to None"""
    User = apps.get_model('users', 'User')
    db_alias = schema_editor.connection.alias
    
    User.objects.using(db_alias).update(guid=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # Step 1: Add field without unique constraint (nullable)
        migrations.AddField(
            model_name='user',
            name='guid',
            field=models.UUIDField(
                default=uuid.uuid4, 
                editable=False, 
                null=True, 
                blank=True,
                verbose_name='شناسه یکتا جهانی'
            ),
        ),
        
        # Step 2: Generate GUIDs for existing users
        migrations.RunPython(
            generate_guids_for_existing_users,
            reverse_generate_guids,
        ),
        
        # Step 3: Make field non-nullable
        migrations.AlterField(
            model_name='user',
            name='guid',
            field=models.UUIDField(
                default=uuid.uuid4, 
                editable=False, 
                null=False,
                verbose_name='شناسه یکتا جهانی'
            ),
        ),
        
        # Step 4: Add unique constraint
        migrations.AlterField(
            model_name='user',
            name='guid',
            field=models.UUIDField(
                default=uuid.uuid4, 
                editable=False, 
                unique=True,
                verbose_name='شناسه یکتا جهانی'
            ),
        ),
    ]
