# Generated by Django 5.2.5 on 2025-09-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='آدرس کامل تصویر پروفایل کاربر', null=True, verbose_name='آدرس تصویر پروفایل'),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='نام کامل نمایشی کاربر', max_length=100, null=True, verbose_name='نام نمایشی'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(default='us-east', help_text='منطقه جغرافیایی کاربر', max_length=50, verbose_name='منطقه'),
        ),
    ]
