# Generated by Django 5.2.5 on 2025-09-06 14:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام اپلیکیشن')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='دامنه')),
                ('client_id', models.CharField(max_length=100, unique=True, verbose_name='شناسه کلاینت')),
                ('client_secret', models.CharField(max_length=255, verbose_name='رمز کلاینت')),
                ('redirect_uri', models.URLField(verbose_name='آدرس بازگشت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'کلاینت SSO',
                'verbose_name_plural': 'کلاینت\u200cهای SSO',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SSOAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'ورود'), ('logout', 'خروج'), ('token_issued', 'صدور توکن'), ('token_validated', 'اعتبارسنجی توکن'), ('redirect', 'انتقال'), ('error', 'خطا')], max_length=20, verbose_name='عمل')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='جزئیات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sso.ssoclient', verbose_name='کلاینت')),
            ],
            options={
                'verbose_name': 'لاگ حسابرسی SSO',
                'verbose_name_plural': 'لاگ\u200cهای حسابرسی SSO',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SSOSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=255, verbose_name='وضعیت')),
                ('redirect_uri', models.URLField(verbose_name='آدرس بازگشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sso.ssoclient', verbose_name='کلاینت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'جلسه SSO',
                'verbose_name_plural': 'جلسات SSO',
                'ordering': ['-created_at'],
            },
        ),
    ]
