# Generated by Django 5.2.5 on 2025-09-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssosession',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وضعیت'),
        ),
    ]
