# Generated by Django 5.2.5 on 2025-09-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0002_alter_ssosession_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssosession',
            name='state',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='وضعیت'),
        ),
    ]
