# Generated by Django 5.2.5 on 2025-09-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0005_add_allow_any_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssoclient',
            name='redirect_uri',
            field=models.URLField(verbose_name='آدرس بازگشت اصلی'),
        ),
    ]
